# Generated by Django 3.1.5 on 2021-01-19 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0002_issue_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='task_id',
        ),
        migrations.CreateModel(
            name='DateUpdateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, unique=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_task', to='api_projects.issue')),
            ],
        ),
    ]
