# Generated by Django 3.1.5 on 2021-01-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0003_auto_20210119_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateupdatetask',
            name='id',
        ),
        migrations.AlterField(
            model_name='dateupdatetask',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_projects.issue'),
        ),
    ]
