# Generated by Django 3.1.5 on 2021-01-14 14:55

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0003_auto_20210114_1314'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(check=models.Q(due_date__gt=django.db.models.expressions.F('created_date')), name='due_date_greater_constraint'),
        ),
    ]
