# Generated by Django 3.1.5 on 2021-01-18 14:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_projects', '0004_auto_20210114_1455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'owner')},
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
