# Generated by Django 3.1.5 on 2021-01-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0004_auto_20210119_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateupdatetask',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
